# Generated by Django 3.2.9 on 2021-11-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
